import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Sacramento, Manrope } from 'next/font/google';




const manrope = Manrope({
  weight: ['400', '600'], // Regular and semi-bold weights for Manrope
  subsets: ['latin'],
  variable: '--font-manrope',
});

const Sacramento_init = Sacramento (
  {
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-Sacramento',

  }
)

export const metadata: Metadata = {
  title: "Zestful amigos",
  description: "Generated by sahwaz yaser",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Sacramento_init.variable} ${manrope.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
